version: '3'

networks:
  cetus:
    external:
      name: cetus_cetus

services:
  cetus:
    build: .
    image: lycantropos/cetus:latest
    volumes:
      - ./:/cetus/
    entrypoint: python
    command: setup.py test
    environment:
      MYSQL_DB_URI: mysql+pymysql://root:secret@mysql
      POSTGRES_DB_URI: postgresql://cetus:password@postgres
    networks:
      - cetus
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
