version: '3'

networks:
  cetus:

services:
  postgres:
    image: postgres:9.6
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cetus
      - POSTGRES_PASSWORD=password
    networks:
      - cetus
    ports:
      - 5432:5432

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - cetus
    ports:
      - 3306:3306

volumes:
  mysql-data:
  postgres-data:
